version: "2"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  haml-lint:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-1-31-0
  stylelint:
    enabled: false
exclude_patterns:
- "bin/**/*"
- "coverage/**/*"
- "config/**/*"
- "db/**/*"
- "vendor/**/*"
