AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 11

Rails/Date:
  Enabled: false

Style/Documentation:
  Enabled: false

