require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'config/{environments,initializers}/**/*'
    - 'config/{application,boot,environment,puma,spring}.rb'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'config.ru'
  NewCops: enable

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

RSpec:
  Enabled: false

RSpec/BeEql:
  Enabled: true

RSpec/PredicateMatcher:
  Enabled: true

Style/Documentation:
  Enabled: false
