Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Rails/Date:
  Enabled: false

Style/Documentation:
  Enabled: false

# This cop is offended by method calls
# which I think are perfectly clear.
Style/NestedParenthesizedCalls:
  Enabled: false
