require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - './*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
  NewCops: enable

Metrics/AbcSize:
  CountRepeatedAttributes: false

Metrics/BlockLength:
  CountAsOne:
    - array
    - hash
    - heredoc
  IgnoredMethods:
    - configure

    # ActiveSupport::Concern
    - class_methods
    - included
    - prepended

    # FactoryBot
    - define
    - factory
    - trait

    # Gemfile
    - group

    # Rake
    - namespace
    - task

    # RSpec
    - before
    - context
    - describe
    - it

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - heredoc

RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash
    - heredoc

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false
