Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 25

# Tests have long blocks. Not super much we can do about it.
Metrics/BlockLength:
  Exclude: 
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

# I kinda agree with this cop, but most of these are default CRUD
# routes. I think the developer will know where `:edit` came from
# even if it's not defined in the controller.
Rails/LexicallyScopedActionFilter:
  Enabled: false

Style/Documentation:
  Enabled: false

# This cop is offended by method calls that I think are perfectly clear.
Style/NestedParenthesizedCalls:
  Enabled: false
