Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

# Tests have long blocks. Not super much we can do about it.
Metrics/BlockLength:
  Exclude: 
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Rails/Date:
  Enabled: false

# This cop only applies to Rails 5.
Rails/HttpPositionalArguments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

# This cop is offended by method calls
# which I think are perfectly clear.
Style/NestedParenthesizedCalls:
  Enabled: false
