dist: focal
language: ruby
cache:
  bundler: true
  directories:
    - $HOME/.cache/yarn
services:
  - mysql
addons:
  chrome: stable
env:
  global:
    - CC_TEST_REPORTER_ID=029db8a4d83b74b2b01b09670c9a28a9c353175415b61186e87a1d70fe461931
before_install:
  - nvm install 'lts/*'
  - nvm use 'lts/*'
  - npm i -g yarn
  - gem install bundler
install:
  - bundle config set --local deployment 'true'
  - bundle install --jobs=3 --retry=3
  - yarn
before_script:
  - cp config/application.yml.example config/application.yml
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
branches:
  only:
    - master
notifications:
  email:
    on_success: never
    on_failure: change
    recipients: programmers@admin.umass.edu
