language: ruby
sudo: required
services:
  - mysql
  - xvfb
addons:
  chrome: stable
env:
  - 'CODECLIMATE_REPO_TOKEN=029db8a4d83b74b2b01b09670c9a28a9c353175415b61186e87a1d70fe461931 RAILS_ENV=test'
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - cp config/application.yml.example config/application.yml
  - cp config/database.yml.example config/database.yml
  - "export DISPLAY=:99.0"
script:
  - bundle exec rake db:create
  - bundle exec rspec
  - bundle exec codeclimate-test-reporter
branches:
  only:
    - master
notifications:
  email:
    on_success: never
    on_failure: change
    recipients: programmers@admin.umass.edu
