language: ruby
rvm: 2.4.1
sudo: required
addons:
  chrome: stable
env:
  - 'CODECLIMATE_REPO_TOKEN=029db8a4d83b74b2b01b09670c9a28a9c353175415b61186e87a1d70fe461931 RAILS_ENV=test'
before_script:
  - bundle update --bundler
  - cp config/application.yml.example config/application.yml
  - cp config/database.yml.example config/database.yml
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give Xvfb time to start
script: 
  - bundle exec rake db:create 
  - bundle exec rspec
  - bundle exec codeclimate-test-reporter
branches:
  only:
    - master
notifications:
  email:
    on_success: never
    on_failure: change
    recipients: programmers@admin.umass.edu
